# Generated by Django 2.2.6 on 2020-02-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table='usuarios_cuidad',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='usuarios_cliente',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='usuarios_departamento',
        ),
    ]
